spring:
  application:
    name: singularity
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/video?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
video:
  path: D://javaproduct//USST_video_player_backend//src//main//resources//static//
